package com.trolmastercard.sexmod;

import java.util.HashMap;
import java.util.Map;
import java.util.Random;
import net.minecraft.entity.Entity;

/** Maps original Bedrock sound keyframes to the sound-event names in the supplied assets. */
final class PortCueRegistry {
    private static final Map<String, String[]> CUES = new HashMap<String, String[]>();

    static {
        CUES.put("allie|aftermoan", new String[]{"girls.allie.aftersessionmoan.aftersessionmoan#4"});
        CUES.put("allie|cum", new String[]{"misc.inserts.inserts#5"});
        CUES.put("allie|deepthroat_cumMSG1", new String[]{"girls.allie.moan.moan#8", "girls.allie.lipsound.lipsound#14", "misc.cuminflation.cuminflation#1"});
        CUES.put("allie|deepthroat_fastMSG1", new String[]{"girls.allie.bjmoan.bjmoan#14"});
        CUES.put("allie|deepthroat_normal_prepareMSG1", new String[]{"girls.allie.giggle.giggle#5"});
        CUES.put("allie|deepthroat_prepareMSG1", new String[]{"girls.allie.giggle.giggle#5"});
        CUES.put("allie|deepthroat_prepareMSG2", new String[]{"girls.allie.sigh.sigh0"});
        CUES.put("allie|deepthroat_slowMSG1", new String[]{"girls.allie.lipsound.lipsound#14", "girls.allie.bjmoan.bjmoan#14"});
        CUES.put("allie|fastMoan", new String[]{"girls.allie.moan.moan#8"});
        CUES.put("allie|giggle", new String[]{"girls.allie.giggle.giggle#5"});
        CUES.put("allie|mmm", new String[]{"girls.allie.mmm.mmm#10"});
        CUES.put("allie|moan", new String[]{"girls.allie.moan.moan#8"});
        CUES.put("allie|pounding", new String[]{"misc.pounding.pounding#35"});
        CUES.put("allie|rich_MSG1", new String[]{"misc.plob.plob#1"});
        CUES.put("allie|scream", new String[]{"misc.scream.scream#2"});
        CUES.put("allie|slide", new String[]{"misc.slide.slide#7"});
        CUES.put("allie|slowMoan", new String[]{"girls.allie.ahh.ahh#10"});
        CUES.put("allie|summonMSG1", new String[]{"girls.allie.scawy.scawy0"});
        CUES.put("allie|summonMSG2", new String[]{"girls.allie.giggle.giggle#5"});
        CUES.put("allie|summonMSG4", new String[]{"girls.allie.lightbreathing.lightbreathing2"});
        CUES.put("allie|summonMSG5", new String[]{"girls.allie.hmph.hmph4"});
        CUES.put("allie|summonMSG6", new String[]{"girls.allie.giggle.giggle3"});
        CUES.put("allie|summonMSG8", new String[]{"girls.allie.huh.huh#2"});
        CUES.put("allie|summon_normalMSG1", new String[]{"girls.allie.giggle.giggle#5"});
        CUES.put("allie|summon_normalMSG3", new String[]{"girls.allie.hmph.hmph4"});
        CUES.put("allie|summon_normalMSG5", new String[]{"girls.allie.huh.huh#2"});
        CUES.put("allie|summon_sandMSG1", new String[]{"girls.allie.scawy.scawy2"});
        CUES.put("bee|sex_cumMSG1", new String[]{"misc.cuminflation.cuminflation#1", "misc.pounding.pounding#35"});
        CUES.put("bee|sex_fastMSG1", new String[]{"misc.pounding.pounding#35"});
        CUES.put("bee|sex_startMSG1", new String[]{"misc.pounding.pounding#35"});
        CUES.put("bia|anal_cumMSG2", new String[]{"girls.bia.ahh.ahh#8"});
        CUES.put("bia|anal_prepareMSG1", new String[]{"misc.plob.plob0"});
        CUES.put("bia|anal_prepareMSG2", new String[]{"misc.bedrustle.bedrustle0"});
        CUES.put("bia|anal_slowMSG1", new String[]{"misc.pounding.pounding#35", "girls.bia.ahh.ahh#8"});
        CUES.put("bia|anal_startMSG1", new String[]{"girls.bia.mmm.mmm3", "misc.pounding.pounding34"});
        CUES.put("bia|anal_startMSG2", new String[]{"misc.pounding.pounding#35", "girls.bia.ahh.ahh#8"});
        CUES.put("bia|cum", new String[]{"misc.inserts.inserts#5"});
        CUES.put("bia|doggyMoan", new String[]{"girls.bia.ahh.ahh#8", "girls.bia.mmm.mmm#8"});
        CUES.put("bia|headpatMSG1", new String[]{"girls.bia.breath.breath0"});
        CUES.put("bia|headpatMSG2", new String[]{"girls.bia.mmm.mmm0"});
        CUES.put("bia|headpatMSG3", new String[]{"girls.bia.huh.huh0"});
        CUES.put("bia|headpatMSG4", new String[]{"girls.bia.giggle.giggle1"});
        CUES.put("bia|orgasm1", new String[]{"girls.bia.mmm.mmm6"});
        CUES.put("bia|orgasm2", new String[]{"girls.bia.mmm.mmm7"});
        CUES.put("bia|pound", new String[]{"misc.pounding.pounding#35"});
        CUES.put("bia|sitdownMSG1", new String[]{"girls.bia.breath.breath#4"});
        CUES.put("bia|slide", new String[]{"misc.slide.slide#7"});
        CUES.put("bia|stripMSG1", new String[]{"girls.bia.giggle.giggle#3"});
        CUES.put("bia|talk_hornyMSG1", new String[]{"girls.bia.hey.hey#4"});
        CUES.put("bia|talk_hornyMSG2", new String[]{"girls.bia.giggle.giggle2"});
        CUES.put("bia|talk_hornyMSG3", new String[]{"girls.bia.breath.breath0"});
        CUES.put("bia|talk_hornyMSG4", new String[]{"girls.bia.huh.huh0"});
        CUES.put("bia|talk_responseMSG1", new String[]{"girls.bia.huh.huh2"});
        CUES.put("bia|talk_responseMSG2", new String[]{"girls.bia.breath.breath1"});
        CUES.put("bia|talk_responseMSG3", new String[]{"girls.bia.giggle.giggle0"});
        CUES.put("ellie|bedRustle", new String[]{"misc.pounding.pounding#35", "misc.bedrustle.bedrustle0"});
        CUES.put("ellie|bedRustle1", new String[]{"misc.bedrustle.bedrustle1"});
        CUES.put("ellie|carry_introMSG1", new String[]{"girls.ellie.hmph.hmph#4"});
        CUES.put("ellie|carry_introMSG2", new String[]{"girls.ellie.giggle.giggle3"});
        CUES.put("ellie|cowgirlStartMSG0", new String[]{"girls.ellie.giggle.giggle4"});
        CUES.put("ellie|cowgirlStartMSG2", new String[]{"girls.ellie.ahh.ahh#10", "misc.pounding.pounding#35"});
        CUES.put("ellie|cowgirlcumMSG1", new String[]{"girls.ellie.ahh.ahh#10", "misc.pounding.pounding#35"});
        CUES.put("ellie|cowgirlcumMSG2", new String[]{"girls.ellie.moan.moan5", "misc.pounding.pounding#35"});
        CUES.put("ellie|cowgirlcumMSG3", new String[]{"misc.pounding.pounding#35"});
        CUES.put("ellie|cowgirlcumMSG5", new String[]{"girls.ellie.goodboy.goodboy#2"});
        CUES.put("ellie|cowgirlfastMSG1", new String[]{"girls.ellie.ahh.ahh#10", "misc.pounding.pounding#35"});
        CUES.put("ellie|cowgirlfastdomMSG1", new String[]{"misc.pounding.pounding#35"});
        CUES.put("ellie|cum", new String[]{"misc.inserts.inserts#5", "misc.pounding.pounding#35"});
        CUES.put("ellie|hugMSG2", new String[]{"girls.ellie.hmph.hmph3"});
        CUES.put("ellie|hugMSG3", new String[]{"girls.ellie.huh.huh1"});
        CUES.put("ellie|hugMSG4", new String[]{"girls.ellie.mommyhorny.mommyhorny#2"});
        CUES.put("ellie|hugMSG5", new String[]{"girls.ellie.huh.huh1"});
        CUES.put("ellie|hugselectedMSG1", new String[]{"girls.ellie.hmph.hmph3"});
        CUES.put("ellie|hugselectedMSG2", new String[]{"girls.ellie.giggle.giggle3"});
        CUES.put("ellie|lipsound", new String[]{"girls.allie.lipsound.lipsound#14"});
        CUES.put("ellie|missionary_cumMSG1", new String[]{"girls.ellie.ahh.ahh#10"});
        CUES.put("ellie|missionary_cumMSG2", new String[]{"girls.ellie.goodboy.goodboy#2"});
        CUES.put("ellie|missionary_fastMSG1", new String[]{"misc.pounding.pounding#35", "girls.ellie.moan.moan#9", "girls.ellie.ahh.ahh#10"});
        CUES.put("ellie|missionary_slowMSG1", new String[]{"misc.pounding.pounding#35", "girls.ellie.moan.moan#9", "girls.ellie.ahh.ahh#10"});
        CUES.put("ellie|pound", new String[]{"misc.pounding.pounding#35"});
        CUES.put("ellie|sitdownMSG1", new String[]{"girls.ellie.cometomommy.cometomommy#2"});
        CUES.put("galath|boostSound", new String[]{"girls.galath.lightcharge.lightcharge#5", "misc.flap.flap#4"});
        CUES.put("galath|breath", new String[]{"girls.galath.breathing.breathing#7"});
        CUES.put("galath|clap", new String[]{"misc.clap.clap#1"});
        CUES.put("galath|creampieGalath", new String[]{"misc.smallinserts.smallinserts#5"});
        CUES.put("galath|cum", new String[]{"misc.smallinserts.smallinserts#5"});
        CUES.put("galath|dialog1", new String[]{"girls.galath.dialog.dialog1"});
        CUES.put("galath|dialog5", new String[]{"girls.galath.dialog.dialog5"});
        CUES.put("galath|energy2", new String[]{"misc.beew.beew2"});
        CUES.put("galath|energysound", new String[]{"misc.beew.beew1"});
        CUES.put("galath|flap", new String[]{"misc.flap.flap#4"});
        CUES.put("galath|flapControlled", new String[]{"misc.flap.flap#4"});
        CUES.put("galath|giggle", new String[]{"girls.galath.giggle.giggle#4"});
        CUES.put("galath|giggle0", new String[]{"girls.galath.giggle.giggle0"});
        CUES.put("galath|goodTiming", new String[]{"girls.galath.dialog.dialog4"});
        CUES.put("galath|hmph", new String[]{"girls.galath.hmph.hmph#3"});
        CUES.put("galath|huh", new String[]{"girls.galath.huh.huh#3"});
        CUES.put("galath|lick", new String[]{"girls.allie.lipsound.lipsound#14"});
        CUES.put("galath|lightcharge", new String[]{"girls.galath.lightcharge.lightcharge#5"});
        CUES.put("galath|moan", new String[]{"girls.galath.moan.moan#8"});
        CUES.put("galath|orgasm", new String[]{"girls.galath.orgasm.orgasm#5"});
        CUES.put("galath|pound", new String[]{"misc.pounding.pounding#35"});
        CUES.put("galath|poundRape", new String[]{"misc.pounding.pounding#35"});
        CUES.put("galath|strongcharge", new String[]{"girls.galath.strongcharge.strongcharge#4"});
        CUES.put("galath|switchmoan", new String[]{"girls.galath.breathing.breathing#7", "girls.galath.moan.moan#8", "girls.galath.ahh.ahh#8"});
        CUES.put("galath|tpSound", new String[]{"misc.weoweo.weoweo2"});
        CUES.put("goblin|breedingEnough", new String[]{"misc.plob.plob#1"});
        CUES.put("goblin|breedingFound", new String[]{"misc.plob.plob#1"});
        CUES.put("goblin|breedingHmm", new String[]{"misc.plob.plob#1"});
        CUES.put("goblin|catchAkward", new String[]{"misc.plob.plob#1"});
        CUES.put("goblin|catchEh", new String[]{"misc.plob.plob#1"});
        CUES.put("goblin|catchMe", new String[]{"misc.plob.plob#1"});
        CUES.put("goblin|catchRather", new String[]{"misc.plob.plob#1"});
        CUES.put("goblin|catchWell", new String[]{"misc.plob.plob#1"});
        CUES.put("goblin|cum", new String[]{"misc.smallinserts.smallinserts#5"});
        CUES.put("goblin|cumSound", new String[]{"misc.smallinserts.smallinserts#5"});
        CUES.put("goblin|paizruiUse", new String[]{"misc.plob.plob#1"});
        CUES.put("goblin|paizuriBoth", new String[]{"misc.plob.plob#1"});
        CUES.put("goblin|paizuriChoice", new String[]{"misc.plob.plob#1"});
        CUES.put("goblin|pound", new String[]{"misc.pounding.pounding#35"});
        CUES.put("goblin|smallPound", new String[]{"misc.pounding.pounding#35"});
        CUES.put("goblin|touch", new String[]{"misc.touch.touch#2"});
        CUES.put("jenny|bjcMSG1", new String[]{"girls.jenny.bjmoan.bjmoan1"});
        CUES.put("jenny|bjcMSG2", new String[]{"girls.jenny.bjmoan.bjmoan7"});
        CUES.put("jenny|bjcMSG3", new String[]{"girls.jenny.aftersessionmoan.aftersessionmoan1"});
        CUES.put("jenny|bjcMSG4", new String[]{"girls.jenny.lightbreathing.lightbreathing0"});
        CUES.put("jenny|bjcMSG5", new String[]{"girls.jenny.lightbreathing.lightbreathing1"});
        CUES.put("jenny|bjcMSG6", new String[]{"girls.jenny.lightbreathing.lightbreathing2"});
        CUES.put("jenny|bjcMSG7", new String[]{"girls.jenny.lightbreathing.lightbreathing3"});
        CUES.put("jenny|bjiMSG1", new String[]{"girls.jenny.mmm.mmm8"});
        CUES.put("jenny|bjiMSG11", new String[]{"girls.jenny.lipsound.lipsound#10"});
        CUES.put("jenny|bjiMSG12", new String[]{"girls.jenny.bjmoan.bjmoan#13", "girls.jenny.lipsound.lipsound#10"});
        CUES.put("jenny|bjiMSG2", new String[]{"girls.jenny.lightbreathing.lightbreathing8"});
        CUES.put("jenny|bjiMSG3", new String[]{"girls.jenny.aftersessionmoan.aftersessionmoan0"});
        CUES.put("jenny|bjiMSG4", new String[]{"misc.belljingle.belljingle0"});
        CUES.put("jenny|bjiMSG5", new String[]{"girls.jenny.hmph.hmph1"});
        CUES.put("jenny|bjiMSG6", new String[]{"girls.jenny.lightbreathing.lightbreathing8"});
        CUES.put("jenny|bjiMSG7", new String[]{"girls.jenny.giggle.giggle4"});
        CUES.put("jenny|bjiMSG8", new String[]{"misc.plob.plob0"});
        CUES.put("jenny|bjiMSG9", new String[]{"girls.jenny.giggle.giggle2"});
        CUES.put("jenny|bjtMSG1", new String[]{"girls.jenny.mmm.mmm#9", "girls.jenny.lipsound.lipsound#10"});
        CUES.put("jenny|doggyGoOnBedMSG1", new String[]{"misc.bedrustle.bedrustle0"});
        CUES.put("jenny|doggyGoOnBedMSG2", new String[]{"girls.jenny.lightbreathing.lightbreathing9"});
        CUES.put("jenny|doggyGoOnBedMSG3", new String[]{"girls.jenny.giggle.giggle0"});
        CUES.put("jenny|doggyGoOnBedMSG4", new String[]{"misc.slap.slap0"});
        CUES.put("jenny|doggycumMSG1", new String[]{"misc.cuminflation.cuminflation0", "misc.pounding.pounding#35", "girls.jenny.moan.moan#8"});
        CUES.put("jenny|doggycumMSG2", new String[]{"girls.jenny.heavybreathing.heavybreathing4"});
        CUES.put("jenny|doggycumMSG3", new String[]{"girls.jenny.heavybreathing.heavybreathing5"});
        CUES.put("jenny|doggycumMSG4", new String[]{"girls.jenny.heavybreathing.heavybreathing6"});
        CUES.put("jenny|doggycumMSG5", new String[]{"girls.jenny.heavybreathing.heavybreathing7"});
        CUES.put("jenny|doggyfastMSG1", new String[]{"misc.pounding.pounding#35", "girls.jenny.moan.moan#8", "girls.jenny.heavybreathing.heavybreathing#8", "girls.jenny.ahh.ahh#10"});
        CUES.put("jenny|doggyslowMSG1", new String[]{"misc.pounding.pounding#35", "girls.jenny.mmm.mmm#9", "girls.jenny.moan.moan#8", "girls.jenny.heavybreathing.heavybreathing#8"});
        CUES.put("jenny|doggyslowMSG2", new String[]{"girls.jenny.lightbreathing.lightbreathing#12"});
        CUES.put("jenny|doggystartMSG1", new String[]{"misc.touch.touch0"});
        CUES.put("jenny|doggystartMSG2", new String[]{"misc.touch.touch1"});
        CUES.put("jenny|doggystartMSG3", new String[]{"misc.bedrustle.bedrustle1"});
        CUES.put("jenny|doggystartMSG4", new String[]{"misc.smallinserts.smallinserts#5", "girls.jenny.mmm.mmm1"});
        CUES.put("jenny|doggystartMSG5", new String[]{"misc.pounding.pounding#35", "girls.jenny.moan.moan#8"});
        CUES.put("jenny|paizuriFastMSG1", new String[]{"misc.pounding.pounding#35", "girls.jenny.mmm.mmm#9", "girls.jenny.ahh.ahh#10"});
        CUES.put("jenny|paizuriSlowMSG1", new String[]{"misc.pounding.pounding#35"});
        CUES.put("jenny|paizuriStartMSG1", new String[]{"misc.pounding.pounding#35"});
        CUES.put("jenny|paymentMSG1", new String[]{"girls.jenny.huh.huh1"});
        CUES.put("jenny|paymentMSG2", new String[]{"misc.plob.plob0"});
        CUES.put("jenny|paymentMSG3", new String[]{"girls.jenny.giggle.giggle#5"});
        CUES.put("jenny|paymentMSG4", new String[]{"misc.plob.plob0"});
        CUES.put("jenny|stripMSG1", new String[]{"girls.jenny.giggle.giggle#5"});
        CUES.put("kobold|analHardMSG1", new String[]{"girls.kobold.moan.moan#10"});
        CUES.put("kobold|bjmoan", new String[]{"girls.kobold.bjmoan.bjmoan#10"});
        CUES.put("kobold|blowjobStartbreath", new String[]{"girls.kobold.lightbreathing.lightbreathing#12"});
        CUES.put("kobold|breath", new String[]{"girls.kobold.lightbreathing.lightbreathing#12"});
        CUES.put("kobold|cum", new String[]{"misc.smallinserts.smallinserts#5"});
        CUES.put("kobold|cumLoud", new String[]{"misc.smallinserts.smallinserts#5"});
        CUES.put("kobold|cumMsg", new String[]{"girls.kobold.sad.sad#3"});
        CUES.put("kobold|cumQuiet", new String[]{"misc.smallinserts.smallinserts#5"});
        CUES.put("kobold|giggle", new String[]{"girls.kobold.giggle.giggle#4"});
        CUES.put("kobold|haa", new String[]{"girls.kobold.haa.haa#7"});
        CUES.put("kobold|interested", new String[]{"girls.kobold.interested.interested#3"});
        CUES.put("kobold|lipsound", new String[]{"girls.allie.lipsound.lipsound#14", "girls.jenny.lipsound.lipsound#10"});
        CUES.put("kobold|moan", new String[]{"girls.kobold.moan.moan#10"});
        CUES.put("kobold|moanMating", new String[]{"girls.kobold.moan.moan#10"});
        CUES.put("kobold|orgasm", new String[]{"girls.kobold.orgasm.orgasm#4"});
        CUES.put("kobold|paymentMSG1", new String[]{"misc.plob.plob#1"});
        CUES.put("kobold|plob", new String[]{"misc.plob.plob#1"});
        CUES.put("kobold|pounding", new String[]{"misc.pounding.pounding#35"});
        CUES.put("kobold|renderEgg", new String[]{"misc.plob.plob#1"});
        CUES.put("kobold|touch", new String[]{"misc.touch.touch#2"});
        CUES.put("kobold|yep", new String[]{"girls.kobold.yep.yep#7"});
        CUES.put("luna|breath", new String[]{"girls.luna.lightbreathing.lightbreathing#25"});
        CUES.put("luna|call_playerMSG1", new String[]{"girls.luna.giggle.giggle#15"});
        CUES.put("luna|cutenya2", new String[]{"girls.luna.cutenya.cutenya2"});
        CUES.put("luna|cutenya3", new String[]{"girls.luna.cutenya.cutenya3"});
        CUES.put("luna|eat", new String[]{"misc.eat.eat#3"});
        CUES.put("luna|eatPay", new String[]{"misc.eat.eat#3"});
        CUES.put("luna|giggle", new String[]{"girls.luna.giggle.giggle#15"});
        CUES.put("luna|happyOh", new String[]{"girls.luna.happyoh.happyoh#8"});
        CUES.put("luna|headpatMSG1", new String[]{"girls.luna.huh.huh#5"});
        CUES.put("luna|headpatMSG2", new String[]{"girls.luna.mmm.mmm#8"});
        CUES.put("luna|headpatMSG3", new String[]{"girls.luna.horninya.horninya0"});
        CUES.put("luna|hehe", new String[]{"girls.luna.giggle.giggle#15"});
        CUES.put("luna|hmph", new String[]{"girls.luna.hmph.hmph#6"});
        CUES.put("luna|horninya", new String[]{"girls.luna.horninya.horninya#10"});
        CUES.put("luna|horninya2", new String[]{"girls.luna.horninya.horninya1", "misc.cuminflation.cuminflation0"});
        CUES.put("luna|huh", new String[]{"girls.luna.huh.huh#5"});
        CUES.put("luna|jump", new String[]{"misc.jump.jump0"});
        CUES.put("luna|moan", new String[]{"girls.luna.moan.moan#10"});
        CUES.put("luna|moanOrNya", new String[]{"girls.luna.moan.moan#10", "girls.luna.horninya.horninya#10"});
        CUES.put("luna|paymentMSG1", new String[]{"misc.plob.plob0"});
        CUES.put("luna|paymentMSG2", new String[]{"girls.luna.huh.huh#5"});
        CUES.put("luna|paymentMSG3", new String[]{"girls.luna.cutenya.cutenya#12"});
        CUES.put("luna|paymentMSG4", new String[]{"girls.luna.owo.owo#8"});
        CUES.put("luna|pounding", new String[]{"misc.pounding.pounding#35"});
        CUES.put("luna|rod_breath", new String[]{"girls.luna.lightbreathing.lightbreathing#25"});
        CUES.put("luna|singing", new String[]{"girls.luna.singing.singing#8"});
        CUES.put("luna|sitting_cumMSG1", new String[]{"girls.luna.horninya.horninya1", "misc.cuminflation.cuminflation0"});
        CUES.put("luna|sitting_fastMSG1", new String[]{"girls.luna.horninya.horninya#10", "girls.luna.moan.moan#10"});
        CUES.put("luna|sitting_introMSG1", new String[]{"girls.luna.giggle.giggle#15"});
        CUES.put("luna|sitting_slowMSG1", new String[]{"girls.luna.horninya.horninya#10", "girls.luna.moan.moan#10", "girls.luna.lightbreathing.lightbreathing#25"});
        CUES.put("luna|touch", new String[]{"misc.touch.touch#2"});
        CUES.put("luna|touch_boobsMSG1", new String[]{"girls.luna.giggle.giggle#15"});
        CUES.put("luna|touch_boobs_cumMSG1", new String[]{"girls.luna.horninya.horninya3"});
        CUES.put("luna|touch_boobs_cumMSG2", new String[]{"girls.luna.horninya.horninya9"});
        CUES.put("luna|touch_boobs_cumMSG3", new String[]{"girls.luna.horninya.horninya1", "misc.cuminflation.cuminflation0"});
        CUES.put("manglelie|doubleSemen0", new String[]{"misc.inserts.inserts#5", "misc.pounding.pounding#35"});
        CUES.put("manglelie|pound", new String[]{"misc.pounding.pounding#35"});
        CUES.put("slime|doggycumMSG1", new String[]{"misc.cuminflation.cuminflation0", "misc.pounding.pounding#35"});
        CUES.put("slime|doggyfastMSG1", new String[]{"misc.pounding.pounding#35"});
        CUES.put("slime|doggyslowMSG1", new String[]{"misc.pounding.pounding#35"});
        CUES.put("slime|doggystartMSG1", new String[]{"misc.touch.touch0"});
        CUES.put("slime|doggystartMSG2", new String[]{"misc.touch.touch1"});
        CUES.put("slime|doggystartMSG4", new String[]{"misc.smallinserts.smallinserts#5"});
        CUES.put("slime|doggystartMSG5", new String[]{"misc.pounding.pounding#35"});
    }

    private PortCueRegistry() { }

    static void play(Entity entity, String character, String cue, Random random) {
        String[] sounds = CUES.get(character + "|" + cue);
        if (sounds == null && "cat".equals(character)) sounds = CUES.get("luna|" + cue);
        if (sounds == null) return;
        for (String descriptor : sounds) {
            int marker = descriptor.lastIndexOf('#');
            String sound = descriptor;
            if (marker >= 0) {
                String prefix = descriptor.substring(0, marker);
                int variants = Integer.parseInt(descriptor.substring(marker + 1));
                sound = prefix + random.nextInt(variants);
            }
            float pitch = 0.96F + random.nextFloat() * 0.08F;
            entity.playSound("sexmod:" + sound, 1.0F, pitch);
        }
    }
}
